### ISSUE TITLE
Documentation: Data Repository Connector Module

### ISSUE THREAD

**Issue by matthewjmckinley** [omeka-s-modules/DataRepositoryConnector#2]
This module is also ready for documentation. The [testing issue](https://github.com/omeka-s-modules/DataRepositoryConnector/issues/1) will be of help, also the DSpace and Fedora Connectors share similar workflows so maybe look there. Happy to answer questions, thanks!

**Comment by katknow** [comment]
Here's the [first draft](https://github.com/katknow/Drafts/blob/e9de612a3cee1e3f9c2e28342b7008442ed364da/datarepositoryconnector.md). Like the other, I'm going to do another proofread in relation to style guide etc. I based it heavily on DSpace and Fedora Connectors like you suggested, which was very helpful. How do you feel about the repetition in the lists for each of the different platforms. I was thinking it was helpful as people might be looking specifically at one, but I don't know if that just bogs down the whole page too much. Do you have thoughts about it? Thanks!

**Comment by matthewjmckinley** [comment]
I think to streamline, you could probably have a "Shared Options" heading or similar for Limit, Files, Comment, Sets/Sites, since they are the same for all services, then have a "Dataverse Options", "Zenodo Options" etc. where you list the more specific URL and metadata format options. 

I'd also suggest **bolding** the option names both at the beginning of the bullet list entry and where they are mentioned again, i.e. 
- **Dataverse Identifier**: The identifier of the Dataverse to import from. If blank, all datasets under **Main Dataverse URL** will be imported.

I just think it looks a little clearer.

Finally I don't know if you need a screenshot for each data service entry screen, maybe cut that down to one example. But it's up to you.

Otherwise, looks great!

**Comment by katknow** [comment]
Those are great suggestions, thanks! Here's the [updated version](https://github.com/katknow/Drafts/blob/e09648b8a776f930006f0be45556ff1b8ca3eb6f/datarepositoryconnector.md). If this works for you, I'll move it over to the proper repo.

**Comment by matthewjmckinley** [comment]
Looks good to me!
