### ISSUE TITLE
Interface

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-modules/DataRepositoryConnector#6]
A couple things about the Past Imports page:

![interface](https://user-images.githubusercontent.com/28012148/212979388-a991f20d-7888-41e6-a19d-50f51c7bd8af.PNG)

1. The Link column isn't so useful - it just shows "zenodo.org" for Zenodo obviously, and not the individual community you grabbed. Maybe that can link to the full url with ID instead, and maybe it can actually show "zenodo.org/communities/ID" instead of "link"? The non-zenodo ones are fine, though they don't always say helpful things like "dataverse.whatever.org".
2. In conjunction with the Link column, we can say which type of import it was (of the four). "Import Type" (Zenodo, Dataverse, etc) and then "Source" ("https://data.humdata.org/" etc) as two columns, or one ("Zenodo: dighl" or "CKAN: https://data.gov"), would be useful.
3. Having done a bunch of test imports now, I wish I could go back and retroactively edit some notes into the Comments field. Is there any way to enable that? Probably not, but I thought I'd put that in as a request.
4. I know some of our imports can be dynamically updated from source by running another import that I guess points to the same source IDs or URLs. Is there any way to shortcut this with a handy button on the past job's page?
5. It would be great if this (and other import modules) could link directly to a search-result of the relevant items. I don't think there's any way for me to search items by "items from Job ID" or "items from Zenodo imports" or anything like that. "Added: 56" being a link to the item subset would be ideal.

**Comment by allanaaa** [comment]
6. As we talked about yesterday, it would be nice to limit the total number of items imported from a source. This would be good for users to check that the connection works, see how the metadata from their chosen source gets crosswalked, etc. This would be preferable to simply having them test with a different small collection that we suggest. I think an input where the user specifies the number of records to pull offers the most utility. 
If the import is for teaching purposes, then having 100 or 200 records rather than thousands may be the goal. If people use this for testing, the problem is then whether they have to manually delete the 10 or so test items and then go back to do a proper import, or whether we could enable them to resume from records 11-n. Having the test import appear as a separate job, in conjunction with idea 5 above, would mean they could delete the duplicate/test items as a job subset anytime, which seems easier than resuming an existing import without a record limit.

**Comment by matthewjmckinley** [comment]
@allanaaa These have all been implemented (except for #3, as discussed) with the latest commit. Could you test and make sure everything is working on your end? I'm also working on porting them over to the DSpace and Fedora connectors

**Comment by allanaaa** [comment]
It looks great!
Just an FYI, imports run before updating the module will have a messy little error message, as in the last row of the screenshot (and the "zenodo" link below that isn't working), but it's up to you if you want to worry about that. 
![drc](https://user-images.githubusercontent.com/28012148/221255388-d2cdfce3-b07f-4980-9695-44bb0091398e.PNG)

**Comment by matthewjmckinley** [comment]
Hm yeah, good point--I think I've addressed this in the latest commit, but I don't have any older imports to test on since I re-installed the module while updating. Can you pull the latest code and see if the error message appears? It should now default to the main data repository URL like before if it can't find the individual collection link.

**Comment by allanaaa** [comment]
The error message is still there, but the link has changed (before it just pointed back to the past imports page, now it's going to zenodo.org).

**Comment by matthewjmckinley** [comment]
OK one more time, I wasn't checking if the collection_link argument was set. It should work with latest code

**Comment by allanaaa** [comment]
That did it!
